# Site settings
name: Ani Talakhadze
title: Ani Talakhadze | Full-stack Software Engineer
description: Dependable full-stack software engineer focused on building amazing web apps
url: https://anitalakhadze.github.io/
baseurl: ''
email: talakhadzeani@gmail.com
cover: https://anitalakhadze.github.io/img/og.png
logo: https://anitalakhadze.github.io/img/emojis/technologist.png
resume: https://anitalakhadze.github.io/resume.pdf
social:
  - title: email
    url: mailto:talakhadzeani@gmail.com
  # - title: twitter
  #   url: https://twitter.com/bchiang7
  # - title: instagram
  #   url: https://instagram.com/bchiang7
  # - title: codepen
  #   url: http://codepen.io/bchiang7
  # - title: github
  #   url: https://github.com/anitalakhadze
  # - title: linkedin
  #   url: https://www.linkedin.com/in/bchiang7

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
